FROM golang:1.16 AS build-env

RUN mkdir -p /workspace
WORKDIR /workspace

ENV GOOS=linux
ENV GOARCH=amd64
ENV CGO_ENABLED=0

ADD go.mod go.sum ./

RUN go mod download

ADD . .

RUN go build -o go.plugin github.com/khulnasoft/go.plugin/cmd/goplugin

FROM khulnasoft/khulnasoft

ADD ./mocks/khulnasoft/khulnasoft.conf /etc/khulnasoft/
ADD ./mocks/conf.d /usr/lib/khulnasoft/conf.d
COPY --from=build-env /workspace/go.plugin /usr/libexec/khulnasoft/plugins.d/go.plugin
